### PR TITLE
Fix invalid transaction amount

### LINKED ISSUE #82: ArgumentError at TRNAMT
Some brazilian banks are generating an invalid value for `TRNAMT` tag.

It breaks the line below:

https://github.com/annacruz/ofx/blob/main/lib/ofx/parser/ofx102.rb#L200

```ruby
ArgumentError: invalid value for BigDecimal(): "."
```

Today we're catching the argument error and returning to the user that the file is not valid. But it is a good solution because it invalidates all the file.

We wouldn't like to create a parallel source to treat it.

One solution we found is to treat this argument error inside the gem returning zero.

Is there any chance to be approved a PR resolving this problem?

We'd love to work on it but we don't want to waist our time if it is not a good idea.

Thanks.

### PR DESCRIPTION
**Pull request by marcosdemelo**
Closes #82

### CODE REVIEW

**Review by cesarjr — APPROVED** [review]

**Comment by cesarjr** [comment]
Great job! 🚀🚀🚀

**Comment by cesarjr** [comment]
Hi @annacruz ! Could you please check if this PR has some chance to be merged?

There is a bank in Brazil sending this value wrong 🙄 and it disallows our users to read the entire ofx file, forcing them to edit e fix the tag manually.

Thank you! 😊

**Comment by annacruz** [comment]
Sure @cesarjr sorry for the delay

**Comment by annacruz** [comment]
up to the end of the week I'll bump the version ok?

**Comment by cesarjr** [comment]
Don't worry about that. Now we can get it directly from the main.
Thank you 🧡

**Pull request merged**
