### PR TITLE
Added support for balances containing zero dates (00000000)

### PR DESCRIPTION
**Pull request by douglaslise**
Added support for balances containing zero dates (00000000), what was causing exceptions when parsing these files

### CODE REVIEW

**Comment by annacruz** [comment]
@douglaslise This doesn't nullify the previous test in the same file? What's is the exception when the date is zeros? When this happen?

**Comment by douglaslise** [comment]
@annacruz I think this does not nullify the previous test because this file `bradesco.ofx` is only used in these tests (those I've added).
The exception that was being raised was `ArgumentError: argument out of range` when the execution comes to the last line of [OFX::Parser::OFX102#build_date method](https://github.com/annacruz/ofx/blob/master/lib/ofx/parser/ofx102.rb#L113):
```ruby
  date = "#{year}-#{month}-#{day} "  
  date << "#{hour}:#{minutes}:#{seconds}" if hour && minutes && seconds
  Time.parse(date)
```
Here the `date` variable comes with the value `"0000-00-00"`, causing an error in `Time.parse`.

**Comment by annacruz** [comment]
@douglaslise I've just merged a PR which claims to solve the same problem (and in my analysis was a better approach). Can you just check if it attends you too?

**Comment by douglaslise** [comment]
@annacruz I've watched those changes and it appears that it could solve my problem. But after the merge you did, this repository is not passing in tests anymore (51 failures), so I could not determine exactly if it attend me, neither I was able to solve these errors in tests.
You could see the errors [here in travis](https://travis-ci.org/douglaslise/ofx/jobs/152291105) , where I checked out your master branch and only added travis configs.
Thank you

**Comment by douglaslise** [comment]
@annacruz As the intentions of this pull request were covered by the pull request #13 I would close this. Although, that pull request has broken a lot of tests, whose I have fixed in another pull request ( #18 ).
Additionally, there is an issue ( #17 ) relating the broken tests. This issue could also be closed when mergin the PR #18.
Thank you.

**Pull request closed without merging**
